apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-project3
  namespace: project3
spec:
  schedule: "* * * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - date; echo Hello Class
              image: busybox:1.31
              imagePullPolicy: IfNotPresent
              name: cronjob-simple
          restartPolicy: OnFailure
