apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: project2
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
